In [1]:
import numpy as np

## Creating array

In [2]:
a = np.array([1, 2, 3], dtype=float) 
print(a,type(a), a.dtype)  

[1. 2. 3.] <class 'numpy.ndarray'> float64


In [3]:
array = np.array([4,3,5,2,4,2,5,8,7,5])
print(array)

[4 3 5 2 4 2 5 8 7 5]


In [4]:
array = np.arange(0,10,dtype=float)


reshaped = array.reshape(-1,2)
print(reshaped)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [5]:
ini = np.ones((3,5))
print(ini)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
ini = np.zeros((4,5))
print(ini)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
np.random.random((4,3))

array([[0.82739216, 0.07085348, 0.28942837],
       [0.83471074, 0.85943795, 0.60831198],
       [0.67931829, 0.65879843, 0.7894256 ],
       [0.37859266, 0.19289549, 0.68166811]])

In [8]:
print(np.linspace(-10,19,15))

[-10.          -7.92857143  -5.85714286  -3.78571429  -1.71428571
   0.35714286   2.42857143   4.5          6.57142857   8.64285714
  10.71428571  12.78571429  14.85714286  16.92857143  19.        ]


In [9]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array attributes

In [10]:
a1 = np.arange(10)

In [11]:
a2 = np.arange(12,dtype=float).reshape(6,2)

In [12]:
a3 = np.arange(8).reshape(2,2,2)

In [13]:
a2.ndim

2

In [14]:
a2.shape

(6, 2)

In [15]:
a1.size

10

In [16]:
a2.itemsize

8

In [17]:
a1.dtype

dtype('int64')

## Changing datatype

In [18]:
a2.astype(np.int32)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]], dtype=int32)

## Array functions


In [19]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[76., 24., 33.],
       [76., 92., 65.],
       [83., 50., 11.]])

In [20]:
# Max/Min/prod/Sum 
np.max(a1)

92.0

In [21]:
np.min(a1,axis=1)
# 0 -> Column and 1 -> Row

array([24., 65., 11.])

In [22]:
# mean/medium/std/var
np.mean(a1)


56.666666666666664

In [23]:
# Dot product of matrixes

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12).reshape(4,3)

np.dot(a1,a2)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [24]:
#Log and exponent
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [25]:
# Round floor ceil
np.round(np.random.random((2,3))*100)

array([[95., 83., 23.],
       [84., 17., 63.]])