In [1]:
import numpy as np

## Creating array

In [2]:
a = np.array([1, 2, 3], dtype=float) 
print(a,type(a), a.dtype)  

[1. 2. 3.] <class 'numpy.ndarray'> float64


In [3]:
array = np.array([4,3,5,2,4,2,5,8,7,5])
print(array)

[4 3 5 2 4 2 5 8 7 5]


In [4]:
array = np.arange(0,10,dtype=float)


reshaped = array.reshape(-1,2)
print(reshaped)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [5]:
ini = np.ones((3,5))
print(ini)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
ini = np.zeros((4,5))
print(ini)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
print(np.random.random((4,3)))

[[0.99851593 0.09328689 0.07369404]
 [0.39939299 0.15791395 0.27676132]
 [0.48467576 0.51630041 0.85476291]
 [0.20071876 0.49536755 0.76219437]]


In [8]:
print(np.linspace(-10,19,15))

[-10.          -7.92857143  -5.85714286  -3.78571429  -1.71428571
   0.35714286   2.42857143   4.5          6.57142857   8.64285714
  10.71428571  12.78571429  14.85714286  16.92857143  19.        ]


In [9]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array attributes

In [10]:
a1 = np.arange(10)

In [11]:
a2 = np.arange(12,dtype=float).reshape(6,2)

In [12]:
a3 = np.arange(8).reshape(2,2,2)

In [13]:
a2.ndim

2

In [14]:
a2.shape

(6, 2)

In [15]:
a1.size

10

In [16]:
a2.itemsize

8

In [17]:
a1.dtype

dtype('int64')

## Changing datatype

In [18]:
a2.astype(np.int32)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]], dtype=int32)

In [ ]:
testing
