In [ ]:
import numpy as np
a = [1,2,3,4,5,6]
array_numbers = np.array(b)

In [ ]:
a = [1,2,3]
b = [4,5,6]
array_a = np.array(a)
array_b = np.array(b)

In [ ]:
print(a+b)

[1, 2, 3, 4, 5, 6]


In [ ]:
print(array_a + array_b)

[5 7 9]


In [ ]:
print(array_a * 7)

[ 7 14 21]


In [ ]:
# understanding dimentions and some other useful functions
array_1 = np.array([1,2,3])
array = np.array([[2,3,4],[1,2,3]])
array

array([[2, 3, 4],
       [1, 2, 3]])

In [ ]:
np.shape(array_1)
np.ndim(array)
np.size(array)

6

In [ ]:
# Creating special array
np.zeros(3)
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# arrange(start , end , step , dtype=int)
np.arange(0,20,2 ,dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [ ]:
# Use to create linearly spaced numbers (np.linspace(start,end, No of numbers))
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

**Indexing**

In [ ]:
numbers_array = np.arange(1,13)
numbers_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
slice_array = numbers_array[1:5]
slice_array

array([2, 3, 4, 5])

In [ ]:
# 2D array slicing
numbers_array_2 = numbers_array.reshape(4,3)
numbers_array_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
numbers_array_2[:,2]

array([ 3,  6,  9, 12])

In [132]:
# Basics Math operation
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b
a - b
a * b
a / b

array([0.25, 0.4 , 0.5 ])

In [135]:
# Reshaping
array = np.arange(1,21).reshape(5,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [141]:
# Matrix mulplitication
array_1 = np.array([
    [1,2,3],
     [4,5,6]])
array_2 = np.array([
    [7,8,9],
     [10,11,12],
    [2,4,5]])

array_1 @ array_2

array([[ 33,  42,  48],
       [ 90, 111, 126]])

In [146]:
# Generating random numbers
np.random.rand(2,10)

array([[0.04027573, 0.13250885, 0.30988195, 0.00246565, 0.44608942,
        0.02192632, 0.97421752, 0.66217766, 0.76530789, 0.4722852 ],
       [0.85110078, 0.39673789, 0.53596813, 0.42763998, 0.4129727 ,
        0.48183935, 0.86253485, 0.72653245, 0.47501425, 0.12744969]])

In [149]:
# Random integers
np.random.randint(1,10,(2,4)) #(start , end (col,row))

array([[6, 1, 7, 4],
       [4, 4, 7, 4]])